spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#Configuration for email sender:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#Configuration for Swagger-UI
springfox:
  documentation:
    enabled: true

