server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:tc:postgresql:13.4:///test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
#    defer-datasource-initialization: true